# Generated by Django 3.0.6 on 2020-05-22 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BRMapp', '0002_brmuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brmuser',
            old_name='nickname',
            new_name='name',
        ),
    ]
