# Generated by Django 3.0.6 on 2020-05-22 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BRMapp', '0003_auto_20200523_0157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brmuser',
            name='user',
        ),
        migrations.AlterField(
            model_name='brmuser',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
