# Generated by Django 3.0.6 on 2020-05-22 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BRMapp', '0008_brmuser_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brmuser',
            name='user',
        ),
    ]
